name: devops test

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Setup Java-17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: checkout
      uses: actions/checkout@v4

    - name: Grant execute permission for gradlew
      working-directory: docker-project
      run:
        chmod +x ./gradlew

    - name: create image
      working-directory: docker-project
      run:
        ./gradlew buildDgocker 
